# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0978bc1cd6d18fa467650ed136b4a30021f0260a41b45583bb910242d8e7b5e2270494ef9f154656e7e7a2f39810f47b63c141bfdf5f52017f7d4b862be5c82a

test:
  secret_key_base: 9f4097a38c205521820c753bc57a045412ca7aabbccac32d7339ec4c5fee6a8096e277be2d2868a8fdfd82d8b63e9cec8607004a90e128fb6b84c82faa18294a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
